# Generated by Django 4.2 on 2025-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_stripe_session_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="location",
            field=models.CharField(default="Processing warehouse", max_length=255),
        ),
    ]
